# Generated by Django 4.1.12 on 2023-10-31 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradersdetails',
            name='application_date',
        ),
        migrations.AddField(
            model_name='tradersdetails',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='tradersdetails',
            name='date_registered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tradersdetails',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=50),
        ),
    ]
