# Generated by Django 4.1.12 on 2023-11-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_tradersdetails_application_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradersDetails',
        ),
    ]
