# Generated by Django 4.1.12 on 2023-11-01 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_delete_tradersdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('trader_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_registered', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=100.0, max_digits=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=100.0, max_digits=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Traders Detail',
            },
        ),
    ]
