# Generated by Django 4.1.12 on 2023-10-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=50),
        ),
    ]
